---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/",
  out.width = "100%"
)
```

# The dynamic landscape of peptide function prediction

This curated list collects peer-reviewed machine learning models dedicated to predicting specific properties of peptides. 
For an interactive and browse-able list, please visit: https://biogenies.info/peptide-prediction-list/.

```{r, echo=FALSE,message=FALSE,results='asis'}
library(glue)
library(magrittr)
library(dplyr)

write_entry <- function(x) {
  res <- glue("1. {Database}: [publication](https://doi.org/{doi})", .envir = x)
  
  if(is.character(unlist(x[["link"]])))
    res <- glue(res, "[database]({link})", .sep = "; ", .envir = x)
  
  paste0(res, ".")
}


dat <- readr::read_csv("data/amyloid_db.csv") %>% 
  # filter(`Current status` == "Active") %>% 
  select("Database", "doi", "link", "Focus...3", "Tipe of data", "Includes experimental conditions", "Focus...6",
         "Includes structural information", "Identifies APRs", "sources_and_links", "Current status", "Last updated")


cat_df <- data.frame(categories = c("Active", "Non-active"),
                     nice_names = c("Active", "Non-active"))

all_tools <- sapply(1L:nrow(cat_df), function(ith_category_id) {
  part_dat <- dat %>% filter(`Current status` == cat_df[ith_category_id, "categories"])
  row_order <- order(part_dat[["Database"]])
  paste0(paste0("## ", cat_df[ith_category_id, "nice_names"], "\n\n"),
         paste0(sapply(row_order, function(ith_row)
           write_entry(part_dat[ith_row, ])), 
           collapse = "\n"), "\n\n\n")
})

links <- gsub(pattern = " ", replacement = "-", x = cat_df[["nice_names"]]) %>% 
  gsub(pattern = "[()]", replacement = "", x = .) %>% 
  tolower() %>% 
  paste0("(#", ., ")")

cat(paste0("- [", cat_df[["nice_names"]], "]", links), "\n\n", sep = "\n")

cat(all_tools, sep = "\n")
```

### About and citation

```{r, echo=FALSE,results='asis'}
cat(readLines("./data/citation.md"), sep = "\n")
```
