---
title: Amyloid databases list
output: 
  html_document:
    theme: paper                                                                 
---      

<style type="text/css">
.main-container {
max-width: 1800px;
margin-left: auto;
margin-right: auto;
}
</style>



```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(DT)
library(dplyr)
library(stringr)

dat <- readr::read_csv("../data/amyloid_db.csv", col_select = c(, 1:14), col_types = "fcfffffff?cccf") %>% 
  # filter(`Current status` == "Active") %>% 
  mutate(DOI = paste0("<a href='", doi,"' >", doi %>% 
                        str_remove(., 'https://doi.org/') 
                      %>% str_remove(., 'http://dx.doi.org/'),"</a>"),
         Database = paste0("<a href='", link,"' >", Database, "</a>"),
         `Last updated` = `Last updated` %>% as.Date(., "%d-%m-%Y"),) %>% 
  select("Database", "Focus", "Type of data", "Only amyloids", "Includes experimental conditions", "Usability",
         "Includes structural information", "Identifies APRs", "Current status", "Last updated", "Data sources and links to other db", "DOI") %>% 
  arrange(desc(`Last updated`))


hover_text <- c("Name and link to a database",
                "Focus of database",
                "Type of data database provides",
                "Indicates if database includes only amyloid proteins and peptides",
                "Indicates if database includes experimental conditions",
                "Indicates the database usability",
                "Indicates if database contains structural information of proteins and peptides",
                "Indicates if database identifies amyloidogenic regions of proteins",
                "The data sources of database and links to other databases",
                "The last update",
                "Current status of database",
                "DOI")


headerCallback <- c(
  "function(thead, data, start, end, display){",
  "  var ncols = data[0].length;",
  sprintf("  var shortnames = [%s]",
          paste0(paste0("'",colnames(dat),"'"), collapse = ",")),
  sprintf("  var tooltips = [%s];",
          paste0(paste0("'", hover_text,"'"), collapse = ",")),
  "  for(var i=0; i<ncols; i++){",
  "    $('th:eq('+i+')',thead).attr('title', tooltips[i]).text(shortnames[i]);",
  "  }",
  "}"
)

```

## {.tabset}

### Amyloid-related database list

```{r}
datatable(dat, extensions = c('Buttons', 'FixedColumns', 'FixedHeader', 'ColReorder', 'KeyTable'), 
          filter = "top", style = "bootstrap",
          class = "display",
          rownames = FALSE, escape = FALSE,
          options = list(dom = "Birt", pageLength = nrow(dat), info = FALSE,
                         buttons = c("copy", "csv", "excel", "print"),
                         autoWidth = TRUE,
                         # scrollY = 700,
                         # scrollX = TRUE,
                         scrollCollapse = FALSE,
                         # columnDefs = list(list(width = '200px', targets = c(0))),
                         # fixedColumns = list(leftColumns = 1), #FixedColumns
                         filter = list(clear = FALSE, plain = TRUE),
                         style = "auto",
                         fillContainer = getOption("DT.fillContainer", NULL),
                         # fixedHeader = TRUE, #FixedHeader
                         paging = FALSE,
                         # scrollY = 300,
                         scrollCollapse = TRUE,
                         # fixedHeader = list(header = TRUE, footer = TRUE), #FixedHeader
                         colReorder = TRUE, #ColReorder
                         realtime = FALSE, #ColReorder
                         keys = TRUE, #KeyTable
                        # lengthMenu = list(25, 50, 75, 100, 125, 150),
                         headerCallback = JS(headerCallback))) %>%  
  formatStyle(c( "Focus","Usability", "Includes structural information", "Identifies APRs", "Type of data", "Includes experimental conditions", "Current status"),
              backgroundColor = styleEqual(c(FALSE, TRUE), c('#ededed', '#d6edff')))  %>%
  formatStyle(c("Database","Data sources and links to other db", "Last updated", "DOI"),
              backgroundColor = styleEqual("false", '#ededed', default = '#d6edff'))
```

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
  
<!-- ### Data collection & curation -->

<!-- To collect software for the prediction of peptide activities, we searched PubMed and Google Scholar databases using queries such as "antimicrobial peptide prediction", "anticancer peptide prediction", etc. We focused on the search results that described software or reviewed/compared available tools for the prediction of a given activity.  -->

<!-- Eligibility criteria: -->

<!--  - the tool needs to be published in a peer-review journal until 1st July 2022. -->
<!--  - we include models that are superceded by their next version.  -->

<!-- We manually curated all information for software featured in a 'Software information' tab. To do that we carefully analysed publications describing given software looking for the following information:  -->

<!-- - peptide activities predicted by a model,  -->
<!-- - link to the web server (**Web server** column),  -->
<!-- - link to the model, i.e. a repository with a trained model which can be used for prediction or an address of the model implemented as standalone software (**Model repository** column), -->
<!-- - link to the repository with all the code and data necessary to train/retrain the model (**Training repository** column). -->

<!-- Then, we checked if the links to the web servers provided in the articles were still working and if they function correctly, i.e. provide understandable output after running prediction. This information is indicated in the **Web server activity** and **Web server functionality** columns, respectively.  -->

<!-- The availability of web servers was assessed on October 14th, 2022. The year of publication and the number of citations were obtained from CrossRef on October 14th, 2022.  -->

<!-- We also inspected available code to determine the reproducibility standard (adapted from [Heil et al.](https://doi.org/10.1038/s41592-021-01256-7) and indicated in the **Reproducibility standard** column). We are additionally using the category *below bronze*, when a model does not fulfill criteria even for the bronze category. -->



### About and citation

```{r, echo=FALSE,results='asis'}
cat(readLines("../data/citation.md"), sep = "\n")
```
